/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aluguelveiculosutf.view;

import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MAYKO
 */
public class BuscaVeiculoView extends javax.swing.JDialog {
    DefaultTableModel model = new DefaultTableModel();
    Integer id = 0;

    /**
     * Creates new form tabela
     */
    public BuscaVeiculoView(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        carregaCabecalho();
    }
    
    private void carregaCabecalho(){
        Vector<String> col = new Vector();
        col.add ("Código");
        col.add ("Nome");
        col.add ("CPF");
        col.add ("UF");
        col.add ("Município");
        model.setDataVector(null, col);
        carregaDados();
    }
    
    private void carregaDados(){
//        SessionFactory sf = new AnnotationConfiguration().configure("hibernate.cfg.xml").buildSessionFactory();
//        Session session = sf.openSession();
//        List<Produtor>lista = session.createCriteria(Produtor.class).list();
//        for (Produtor pro : lista) {
//            //System.out.println(uf.getIduf() + " " + uf.getDescricao() + " " + uf.getSigla());
//            model.addRow(new Object[]{
//                pro.getIdprodutor(),
//                pro.getNome(),
//                pro.getCpf(),
//                pro.getMunicipioIdmunicipio().getUfIduf(),
//                pro.getMunicipioIdmunicipio()
//                
//            });
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUf = new javax.swing.JTable();
        OK = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfConsulta = new javax.swing.JTextField();
        OkCpf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfConsulta1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbUf.setModel(model);
        jScrollPane1.setViewportView(jTbUf);

        OK.setText("Ok");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        CANCELAR.setText("Cancelar");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        jLabel1.setText("CONSULTAR VEÍCULO:");

        jLabel2.setText("Valor Locação:");

        jtfConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConsultaKeyReleased(evt);
            }
        });

        OkCpf.setText("OK");
        OkCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkCpfActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo Veículo:");

        jtfConsulta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConsulta1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CANCELAR))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OkCpf)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OkCpf)
                            .addComponent(jtfConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(CANCELAR))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
//        id = MyNumber.parseInt(model.getValueAt(jTbUf.getSelectedRow(), 0));
        //System.out.println(id);
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    public Integer getId(){
        return id;
    }
    
    
    
    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        id = 0;
        dispose();
    }//GEN-LAST:event_CANCELARActionPerformed

    public void Limpar() {
        jtfConsulta.setText("");
//        jtfCpf.setValue(null);
        int contRow = model.getRowCount();
        for (int i = 0; i < contRow; i++) {
            model.removeRow(0);
        }
        //}
        //Retirar = 0;
    }
    
    private void carregaDados(String nome){
//        Limpar();
//        nome = nome.toUpperCase();
//        Session session = HibernateUtil.getSession();
//        //Query q = session.createQuery("from Aluno a where a.nome = ?");
//        Query q = session.createQuery("from Produtor p where upper(p.nome) like ?");
//        q.setString(0,"%" + nome + "%");
//        //q.setString(0, nome);
//        List<Produtor> list = q.list();
//        for (Produtor produtor : list) {
//            model.addRow(new Object[]{
//                produtor.getIdprodutor(),
//                produtor.getNome(),
//                produtor.getCpf(),
//                produtor.getMunicipioIdmunicipio().getUfIduf(),
//                produtor.getMunicipioIdmunicipio()                
//            });
//        }
    }
    
    private void carregaDadosCpf(String cpf){
        Limpar();
        //ra = ra.toUpperCase();
//        Session session = HibernateUtil.getSession();
//        Query q = session.createQuery("from Produtor p where p.cpf = ?");
//        //Query q = session.createQuery("from Aluno a where a.ra like ?");
//        //q.setString(0,"%" + ra + "%");
//        q.setString(0, cpf);
//        List<Produtor> list = q.list();
//        for (Produtor produtor : list) {
//            model.addRow(new Object[]{
//                produtor.getIdprodutor(),
//                produtor.getNome(),
//                produtor.getCpf(),                
//                produtor.getMunicipioIdmunicipio().getUfIduf(),
//                produtor.getMunicipioIdmunicipio()
//            });
//        }
    }
    
    private void jtfConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsultaKeyReleased
        // TODO add your handling code here:
        carregaDados(jtfConsulta.getText());
    }//GEN-LAST:event_jtfConsultaKeyReleased

    private void OkCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkCpfActionPerformed
        // TODO add your handling code here:
//        carregaDadosCpf(jtfCpf.getText());
    }//GEN-LAST:event_OkCpfActionPerformed

    private void jtfConsulta1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsulta1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConsulta1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                BuscaVeiculoView dialog = new BuscaVeiculoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton OK;
    private javax.swing.JButton OkCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUf;
    private javax.swing.JTextField jtfConsulta;
    private javax.swing.JTextField jtfConsulta1;
    // End of variables declaration//GEN-END:variables
}
