/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aluguelveiculosutf.view;

import aluguelveiculosutf.servidor.ServicosServ;
import aluguelveiculosutf.servidor.Veiculo;
import aluguelveiculosutf.util.MyNumber;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MAYKO
 */
public class BuscaVeiculoView extends javax.swing.JDialog {
    DefaultTableModel model = new DefaultTableModel();
    Integer id = 0;
    Veiculo veiculo = null;

    /**
     * Creates new form tabela
     */
    public BuscaVeiculoView(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        carregaCabecalho();
    }

    BuscaVeiculoView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Veiculo getVeiculo() {
        return veiculo;
    }
    
    
    
    private void carregaCabecalho(){
        Vector<String> col = new Vector();
        col.add ("Id");
        col.add ("Modelo");
        col.add ("Marca");
        col.add ("Ano");
        col.add ("Valor Locação");
        model.setDataVector(null, col);
        carregaDados();
    }
    
    private void carregaDados(){
       
        ServicosServ veiculos = ServicosServ.getInstancia();
        int i = 0;
        
        for (Veiculo veiculo1 : veiculos.getListaVeiculo()) {
            //System.out.println(uf.getIduf() + " " + uf.getDescricao() + " " + uf.getSigla());
            model.addRow(new Object[]{
                i + 1,
                veiculo1.getModelo(),
                veiculo1.getMarca(),
                veiculo1.getAno(),
                veiculo1.getValorLocacao()
                
            });
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUf = new javax.swing.JTable();
        OK = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfConsulta = new javax.swing.JTextField();
        OkCpf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTbUf.setModel(model);
        jScrollPane1.setViewportView(jTbUf);

        OK.setText("Ok");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        CANCELAR.setText("Cancelar");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        jLabel1.setText("CONSULTAR VEÍCULO:");

        jtfConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfConsultaActionPerformed(evt);
            }
        });
        jtfConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfConsultaKeyReleased(evt);
            }
        });

        OkCpf.setText("OK");
        OkCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkCpfActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo Veículo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CANCELAR))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(OkCpf)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OkCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(CANCELAR))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        
        id = MyNumber.parseInt(model.getValueAt(jTbUf.getSelectedRow(), 0));
        System.out.println(id);
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    public Integer getId(){
        return id;
    }
    
    
    
    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        id = 0;
        dispose();
    }//GEN-LAST:event_CANCELARActionPerformed

    public void Limpar() {
        jtfConsulta.setText("");
//        jtfCpf.setValue(null);
        int contRow = model.getRowCount();
        for (int i = 0; i < contRow; i++) {
            model.removeRow(0);
        }
        //}
        //Retirar = 0;
    }
    
    private void carregaDados(String nomeVeiculo){
        Limpar();
        ServicosServ buscaVeiculos = ServicosServ.getInstancia();
        int i = 0;
        
        veiculo = buscaVeiculos.buscarVeiculo(nomeVeiculo);
        
        
        model.addRow(new Object[]{
            i + 1,
            veiculo.getModelo(),
            veiculo.getMarca(),
            veiculo.getAno(),
            veiculo.getValorLocacao()

        });
    }
    
    private void jtfConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsultaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConsultaKeyReleased

    private void OkCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkCpfActionPerformed
        // TODO add your handling code here:
        carregaDados(jtfConsulta.getText());
    }//GEN-LAST:event_OkCpfActionPerformed

    private void jtfConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                BuscaVeiculoView dialog = new BuscaVeiculoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton OK;
    private javax.swing.JButton OkCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUf;
    private javax.swing.JTextField jtfConsulta;
    // End of variables declaration//GEN-END:variables
}
